apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-api
  namespace: basil-cs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-api
  template:
    metadata:
      labels:
        app: cs-api
    spec:
      containers:
        - image: registry.digitalocean.com/basil-cs/cs-api:{{ tag }}
          imagePullPolicy: Always
          name: cs-api
          tty: true
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              scheme: HTTP
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: conf
              mountPath: /app/config
      volumes:
        - name: conf
          configMap:
            name: cs-api-conf
