version: "3.7"

services:
  cs-nginx:
    container_name: cs-nginx
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ../cs-api:/cs-api
      - ../cs-web-cms/dist:/cs-web-cms/dist
      - ../cs-web-chat/dist:/cs-web-chat/dist
    restart: always
    networks:
      - backend

  # cs-workspace:
  #   container_name: cs-workspace
  #   image: bitnami/golang:1.18.2
  #   tty: true
  #   ports:
  #     - 8082:8082
  #   volumes:
  #     - ../cs-api:/cs-api
  #   restart: always
  #   networks:
  #     - backend

  cs-mysql:
    container_name: cs-mysql
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: cs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks: 
      - backend
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  cs-redis:
    container_name: cs-redis
    image: redis:5.0.9-buster
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
    volumes:
      - ./redis/data/master:/data
    networks:
      - backend

#  cs-redis-slave:
#    container_name: cs-redis-slave
#    image: redis:5.0.9-buster
#    ports:
#      - "6380:6379"
#    command: redis-server --slaveof cs-redis 6379
#    depends_on:
#      - cs-redis
#    tty: true
#    volumes:
#      - ./redis/data/slave:/data
#    networks:
#      - backend
#
#  cs-redis-sentinel:
#    container_name: cs-redis-sentinel
#    image: redis:5.0.9-buster
#    command: redis-sentinel /conf/sentinel.conf
#    restart: always
#    depends_on:
#      - cs-redis
#      - cs-redis-slave
#    tty: true
#    volumes:
#      - ./redis/conf:/conf
#      - ./redis/log:/var/log/redis
#    networks:
#      - backend

networks:
  backend:
    driver: bridge
